# AI disclosure: Initial boilier plate file was generated by claude. Removed the installation of unnecessary packages and changed
# username and group name. Also removed access to port 8080.
# Use Ubuntu 26.04 as the base image
FROM ubuntu:26.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=UTC \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

# Set a working directory
WORKDIR /app

# Update package lists and install common utilities
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user for security
RUN groupadd --gid 1001 connector_game \
    && useradd --uid 1001 --gid connector_game --shell /bin/bash --create-home connector_game

# Copy application files (adjust as needed)
# COPY . .
COPY *.py .
COPY requirements.txt .

RUN pip install --break-system-packages -r requirements.txt

# Set ownership to non-root user
RUN chown -R connector_game:connector_game /app

# Switch to non-root user
USER connector_game

# Default command
CMD ["/bin/bash"]
